"""Structural Protocol interfaces for illumio_ops domain objects.

These Protocols document the subset of each class that its consumers actually
use. They enable mock-free testing via lightweight structural implementations.
"""
from __future__ import annotations
from typing import Protocol


class IApiClient(Protocol):
    """Subset of ApiClient used by Analyzer and RuleScheduler."""
    def check_health(self) -> tuple[int, str]: ...
    def update_label_cache(self, silent: bool = False, force_refresh: bool = True) -> None: ...
    def fetch_traffic_for_report(self, *args, **kwargs) -> list[dict]: ...
    def get_all_rulesets(self, force_refresh: bool = False) -> list[dict]: ...
    def get_active_rulesets(self) -> list[dict]: ...
    def fetch_events(self, *args, **kwargs) -> list[dict]: ...
    def resolve_actor_str(self, *args, **kwargs) -> list: ...


class IReporter(Protocol):
    """Subset of Reporter used by Analyzer."""
    def send_alerts(self, alert_list: list, resolved_list: list) -> None: ...


class IEventStore(Protocol):
    """Event buffer (append/clear)."""
    def append(self, event: dict) -> None: ...
    def clear(self) -> None: ...
